server:
  port: 8080

spring:
  datasource:
    username: root
    password: student#2205
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update

indexing-settings:
  sites:
    #- url: https://www.edimdoma.ru
    #  name: Едим дома
    #- url: https://www.svetlovka.ru
    #  name: Библиотека
    #- url: https://www.ipfran.ru
    #  name: Институт прикладной физики
    - url: https://madviz.ru
      name: Дальний восток
    - url: https://news.mail.ru
      name: News
    - url: https://pogoda.mail.ru
      name: Погода mail.ru


